export const SETTING_GROUPS = [
  {
    key: "arduino_bridge",
    title: "Connectivity Settings",
    children: [
      {
        type: "button",
        title: "Reconnect Motor Driver",
        description: "If you want to restart or have connection issues, try this.",
        buttonText: "Reconnect",
        loadingText: "Reconnecting...",
        serviceName: "/arduino_bridge/hub_servo_reconnect",
      },
      {
        type: "button",
        title: "Reconnect Arduino",
        description: "If you have sensor reading issues or servo motor misbehavior, try this.",
        buttonText: "Reconnect",
        loadingText: "Reconnecting...",
        serviceName: "/arduino_bridge/arduino_reconnect",
      },
      {
        type: "button",
        title: "Reconnect Aruco Camera",
        description: "If you have issues with the Aruco camera, try this.",
        buttonText: "Reconnect",
        loadingText: "Reconnecting...",
        serviceName: "/aruco_detector/aruco_camera_reconnect",
      },
    ],
  },
  {
    key: "bench_tracker_v3",
    title: "Bench Tracker Settings",
    children: [
    {
        type: "slider",
        title: "Minimum ToF value",
        description: "If the ToF value is below this threshold, the robot will stop to avoid collision.",
        path: "min_tof",
        min: 0,
        max: 50,
        step: 1,
        unit: "mm",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Maximum ToF value",
        description: "If the ToF value is above this threshold, the robot will stop to avoid collision.",
        path: "max_tof",
        min: 400,
        max: 800,
        step: 1,
        unit: "mm",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Bench offset Kp forward",
        description: "Proportional gain for bench tracker when moving forward. Higher values will result in stronger correction but can cause oscillations if set too high.",
        path: "Kp_offset",
        min: 0,
        max: 1,
        step: 0.05,
        unit: "",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Bench offset Kp backward",
        description: "Proportional gain for bench tracker when moving backward. Higher values will result in stronger correction but can cause oscillations if set too high.",
        path: "Kp_offset_b",
        min: 0,
        max: 1,
        step: 0.05,
        unit: "",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Bench offset Kd",
        description: "Derivative gain for bench tracker for both forward and backward movement. Higher values will result in more damping but can cause oscillations if set too high.",
        path: "Kd_offset",
        min: 0,
        max: 10,
        step: 0.1,
        unit: "",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Bench offset D filter t",
        description: "Time constant for the derivative filter in bench tracker for both forward and backward movement. Higher values will result in smoother but less responsive behavior.",
        path: "d_filter_t",
        min: 0,
        max: 1,
        step: 0.05,
        unit: "",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Correction speed. Robot will slow down to this speed when performing any correction",
        description: "Correction speed in RPM",
        path: "corr_rpm",
        min: 1,
        max: 5,
        step: 1,
        unit: "rpm",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Base speed. This is the speed at which the robot will move under normal circumstances",
        description: "Base speed in RPM",
        path: "base_rpm",
        min: 5,
        max: 15,
        step: 1,
        unit: "rpm",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Max speed. This is the maximum speed the robot can reach.",
        description: "Max speed in RPM",
        path: "max_rpm",
        min: 10,
        max: 30,
        step: 1,
        unit: "rpm",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Offset enter threshold",
        description: "The robot will start correcting its position when the offset exceeds this threshold.",
        path: "offset_enter_m",
        min: 0,
        max: 0.2,
        step: 0.005,
        unit: "m",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Offset exit threshold",
        description: "The robot will stop correcting its position when the offset falls below this threshold.",
        path: "offset_exit_m",
        min: 0,
        max: 0.2,
        step: 0.005,
        unit: "m",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Yaw enter threshold",
        description: "Robot will start correcting its yaw when the yaw error exceeds this threshold.",
        path: "yaw_enter_m",
        min: 0,
        max: 0.2,
        step: 0.005,
        unit: "m",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Yaw exit threshold",
        description: "The robot will stop correcting its yaw when the yaw error falls below this threshold.",
        path: "yaw_exit_m",
        min: 0,
        max: 0.2,
        step: 0.005,
        unit: "m",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Aruco centering exit threshold",
        description: "Robot will stop aruco centering when the error falls below this threshold.",
        path: "aruco_center_done_norm",
        min: 0,
        max: 20,
        step: 1,
        unit: "pixels",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Aruco stable frame count",
        description: "Robot will consider the aruco marker centered and stable when it has seen this many consecutive frames.",
        path: "aruco_center_stable_cycles",
        min: 0,
        max: 10,
        step: 1,
        unit: "frames",
        debounceMs: 200,
      },
    ],
  },
  {
    key: "motor_control_mux",
    title: "Drive Motor Settings",
    children: [
      {
        type: "slider",
        title: "Wheel Speed",
        description: "Robot speed in RPM when in manual control mode.",
        path: "manual_rpm",
        min: 1,
        max: 25,
        step: 1,
        unit: "rpm",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Acceleration Time",
        description: "Acceleration time in milliseconds",
        path: "acel_ms",
        min: 20,
        max: 1000,
        step: 10,
        unit: "ms",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Deceleration Time",
        description: "Deceleration time in milliseconds",
        path: "decel_ms",
        min: 20,
        max: 1000,
        step: 10,
        unit: "ms",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Correction Acceleration Time",
        description: "Acceleration time in milliseconds when performing correction",
        path: "acel_ms_corr",
        min: 20,
        max: 1000,
        step: 10,
        unit: "ms",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Correction Deceleration Time",
        description: "Deceleration time in milliseconds when performing correction",
        path: "decel_ms_corr",
        min: 20,
        max: 1000,
        step: 10,
        unit: "ms",
        debounceMs: 200,
      },
    ],
  },
];
