export const SETTING_GROUPS = [
  /*{
    key: "basic",
    title: "Basic Settings",
    children: [
      {
        type: "toggle",
        title: "Drive Mode",
        description: "Manual vs Auto mode",
        path: "drive.mode",
        options: [
          { value: "manual", label: "Manual" },
          { value: "auto", label: "Auto" },
        ],
      },
      {
        type: "number",
        title: "Max RPM",
        description: "Speed limit for manual control",
        path: "limits.max_rpm",
        min: 0,
        max: 60,
        step: 1,
        unit: "rpm",
      },
      {
        type: "slider",
        title: "PID Kp",
        description: "Proportional gain",
        path: "pid.kp",
        min: 0,
        max: 10,
        step: 0.1,
        debounceMs: 200,
      },
    ],
  },*/
  {
    key: "arduino_bridge",
    title: "Connectivity Settings",
    children: [
      {
        type: "button",
        title: "Reconnect Motor Driver",
        description: "Reconnect the hub servo motor driver.",
        buttonText: "Reconnect",
        loadingText: "Reconnecting...",
        serviceName: "/arduino_bridge/hub_servo_reconnect",
      },
      {
        type: "button",
        title: "Reconnect Arduino",
        description: "Reconnect the Arduino.",
        buttonText: "Reconnect",
        loadingText: "Reconnecting...",
        serviceName: "/arduino_bridge/arduino_reconnect",
      },
      {
        type: "button",
        title: "Restart ToF Sensors",
        description: "Restart the ToF sensors only.",
        buttonText: "Restart",
        loadingText: "Restarting...",
        serviceName: "/arduino_bridge/tof_restart",
      },
    ],
  },
  {
    key: "bench_tracker_v2",
    title: "Bench Tracker Settings",
    children: [
      {
        type: "number",
        title: "Bench overall error Kp",
        description: "Proportional gain for bench offset correction",
        path: "Kp_error",
        min: 0,
        max: 1,
        step: 0.01,
        unit: "",
      },
      {
        type: "number",
        title: "Bench offset Kp",
        description: "Proportional gain for bench offset correction",
        path: "Kp_offset",
        min: 0,
        max: 100,
        step: 0.1,
        unit: "",
      },
      {
        type: "number",
        title: "Rotation yaw Kp",
        description: "Proportional gain for rotation yaw correction",
        path: "Kp_yaw",
        min: 0,
        max: 1,
        step: 0.005,
        unit: "",
      },
      {
        type: "slider",
        title: "Base speed",
        description: "Base speed in RPM",
        path: "base_rpm",
        min: 5,
        max: 15,
        step: 1,
        unit: "rpm",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Max speed",
        description: "Max speed in RPM",
        path: "max_rpm",
        min: 10,
        max: 30,
        step: 1,
        unit: "rpm",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Steer angle Kp",
        description: "Proportional gain for steer angle correction",
        path: "k_steer",
        min: 0,
        max: 100,
        step: 1,
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Maximum steer angle",
        description: "Maximum steer angle in degrees",
        path: "max_steer_deg",
        min: 0,
        max: 45,
        step: 5,
        unit: "°",
        debounceMs: 200,
      },
      {
        type: "number",
        title: "Steering servo deadzone",
        description:
          "when this value increase steer servo will be less sensitive",
        path: "w_small",
        min: 0,
        max: 1,
        step: 0.01,
        unit: "",
      },
    ],
  },
  {
    key: "motor_control_mux",
    title: "Drive Motor Settings",
    children: [
      {
        type: "slider",
        title: "Wheel Speed",
        description: "Wheel speed in RPM",
        path: "manual_rpm",
        min: 1,
        max: 25,
        step: 1,
        unit: "rpm",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Deceleration Time",
        description: "Deceleration time in milliseconds",
        path: "decel_ms",
        min: 500,
        max: 1500,
        step: 50,
        unit: "ms",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Acceleration Time",
        description: "Acceleration time in milliseconds",
        path: "acel_ms",
        min: 500,
        max: 1500,
        step: 50,
        unit: "ms",
        debounceMs: 200,
      },
    ],
  },
];
