export const SETTING_GROUPS = [
  {
    key: "arduino_bridge",
    title: "Connectivity Settings",
    children: [
      {
        type: "button",
        title: "Reconnect Motor Driver",
        description: "Reconnect the hub servo motor driver.",
        buttonText: "Reconnect",
        loadingText: "Reconnecting...",
        serviceName: "/arduino_bridge/hub_servo_reconnect",
      },
      {
        type: "button",
        title: "Reconnect Arduino",
        description: "Reconnect the Arduino.",
        buttonText: "Reconnect",
        loadingText: "Reconnecting...",
        serviceName: "/arduino_bridge/arduino_reconnect",
      },
    ],
  },
  {
    key: "bench_tracker_v2",
    title: "Bench Tracker Settings",
    children: [
      {
        type: "slider",
        title: "Bench offset Kp",
        description: "Proportional gain for bench offset correction",
        path: "Kp_offset",
        min: 0,
        max: 10,
        step: 0.05,
        unit: "",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Bench offset Kd",
        description: "Derivative gain for bench offset correction",
        path: "Kd_offset",
        min: 0,
        max: 10,
        step: 0.05,
        unit: "",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Bench offset D filter t",
        description: "Time constant for the derivative filter in bench offset correction",
        path: "d_filter_t",
        min: 0,
        max: 1,
        step: 0.05,
        unit: "",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Correction speed",
        description: "Correction speed in RPM",
        path: "corr_rpm",
        min: 1,
        max: 5,
        step: 1,
        unit: "rpm",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Base speed",
        description: "Base speed in RPM",
        path: "base_rpm",
        min: 5,
        max: 15,
        step: 1,
        unit: "rpm",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Max speed",
        description: "Max speed in RPM",
        path: "max_rpm",
        min: 10,
        max: 30,
        step: 1,
        unit: "rpm",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Offset enter threshold",
        description: "Threshold for entering offset correction",
        path: "offset_enter_m",
        min: 0,
        max: 0.2,
        step: 0.005,
        unit: "m",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Offset exit threshold",
        description: "Threshold for exiting offset correction",
        path: "offset_exit_m",
        min: 0,
        max: 0.2,
        step: 0.005,
        unit: "m",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Yaw enter threshold",
        description: "Threshold for entering yaw correction",
        path: "yaw_enter_m",
        min: 0,
        max: 0.2,
        step: 0.005,
        unit: "m",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Yaw exit threshold",
        description: "Threshold for exiting yaw correction",
        path: "yaw_exit_m",
        min: 0,
        max: 0.2,
        step: 0.005,
        unit: "m",
        debounceMs: 200,
      },
    ],
  },
  {
    key: "motor_control_mux",
    title: "Drive Motor Settings",
    children: [
      {
        type: "slider",
        title: "Wheel Speed",
        description: "Wheel speed in RPM",
        path: "manual_rpm",
        min: 1,
        max: 25,
        step: 1,
        unit: "rpm",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Acceleration Time",
        description: "Acceleration time in milliseconds",
        path: "acel_ms",
        min: 100,
        max: 2500,
        step: 100,
        unit: "ms",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Deceleration Time",
        description: "Deceleration time in milliseconds",
        path: "decel_ms",
        min: 100,
        max: 2500,
        step: 100,
        unit: "ms",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Correction Acceleration Time",
        description: "Acceleration time in milliseconds",
        path: "acel_ms_corr",
        min: 100,
        max: 2500,
        step: 100,
        unit: "ms",
        debounceMs: 200,
      },
      {
        type: "slider",
        title: "Correction Deceleration Time",
        description: "Deceleration time in milliseconds",
        path: "decel_ms_corr",
        min: 100,
        max: 2500,
        step: 100,
        unit: "ms",
        debounceMs: 200,
      },
    ],
  },
];
